openapi: 3.0.4
info:
  title: API de personajes de Marvel Rivals
  description: |
    Una API desarrollada en Python que permite gestionar personajes del universo Marvel Rivals. El proyecto permite agregar personajes nuevos, realizar paginación de resultados, y está conectado con X (Twitter) para obtener publicaciones recientes relacionadas con Marvel Rivals.
  version: 1.0.0
servers:
  - url: http://localhost:8000/
paths:
  /personajes:
    post:
      tags:
        - personajes
      summary: Crear nuevo personaje
      description: Agregar un nuevo personaje a la lista.
      operationId: crearPersonaje
      requestBody:
        description: Personaje a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonajesReqBody'
      responses:
        '200':
          description: Personaje creado exitosamente
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/PersonajeRespuestaExitosa'
        '422':
            description: Datos Invalidos
        default:
            description: El campo 'Nombre' es requerido. Field required
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PersonajesResError'
    get:
      tags:
        - personajes
      summary: Trae la lista de personajes
      description: Trae la lista de los superheroes registrados en la base de datos.
      operationId: getPersonajesList
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Pagina de la lista de elementos, cada pagina es de 10 
      responses:
        '200':
          description: Lista de personajes de Marvel Rivals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Personajes'                
components:
  schemas:
    PersonajesResError:
      type: object
      required:
      - message
      - status
      properties:
        mensaje_error:
          type: array
          items: string
          example:
            - "El campo 'Nombre' es requerido. Field required"
    PersonajesReqBody:
      type: object
      required:
      - Nombre
      - Universo
      - RolDePersonaje
      - Armas
      - Salud
      - origen
      properties:
        Nombre:
          type: string
          example: Groot
        Universo:
          type: string
          example: Marvel
        RolDePersonaje:
          type: string
          example: "Soporte"
        Armas:
          type: string
          example: "Ramas"
        Salud: 
          type: integer
          example: "120"
        origen: 
          type: object
          required: 
            - nombre
            - url
          properties:
            nombre: 
              type: string
              example: "Planeta X"
            url:
              type: string
              example: "https://marvel.com/groot"

    Personajes:
      type: object
      required:
      - id
      - Nombre
      - Universo
      - RolDePersonaje
      - Armas
      - Salud
      - origen
      - FechaCreacion
      properties:
        id:
          type: integer
          example: 1
        Nombre:
          type: string
          example: "Groot"
        Universo:
          type: string
          example: "Marvel"
        RolDePersonaje:
          type: string
          example: "Soporte"
        Armas:
          type: string
          example: "Ramas"
        Salud: 
          type: integer
          example: "120"
        origen: 
          type: object
          required: 
            - nombre
            - url
          properties:
            nombre: 
              type: string
              example: "Planeta X"
            url:
              type: string
              example: "https://marvel.com/groot"
        FechaCreacion:
          type: string
          example: "2025-06-24T20:31:24.099899"
          
    PersonajeRespuestaExitosa:
      type: object
      required:
      - mensaje
      - personaje
      properties:
        mensaje:
          type: string
          example: "Personaje agregado exitosamente"
        personaje:
          $ref: '#/components/schemas/Personajes'
        
    Error:
      type: object
      properties:
        code:
